# -*- coding: utf-8 -*-
"""TicTacToe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_ZSFlYrHT730Z2EZg7ChKjjDGYTM61Y
"""

import math

# Constants
HUMAN = 'X'
AI = 'O'
EMPTY = ' '

def print_board(board):
    print("\n")
    for row in range(3):
        print(f" {board[row][0]} | {board[row][1]} | {board[row][2]} ")
        if row < 2:
            print("---+---+---")
    print("\n")

def is_moves_left(board):
    for row in board:
        if EMPTY in row:
            return True
    return False

def evaluate(board):
    # Check rows
    for row in range(3):
        if board[row][0] == board[row][1] == board[row][2] != EMPTY:
            return 10 if board[row][0] == AI else -10

    # Check columns
    for col in range(3):
        if board[0][col] == board[1][col] == board[2][col] != EMPTY:
            return 10 if board[0][col] == AI else -10

    # Check diagonals
    if board[0][0] == board[1][1] == board[2][2] != EMPTY:
        return 10 if board[0][0] == AI else -10

    if board[0][2] == board[1][1] == board[2][0] != EMPTY:
        return 10 if board[0][2] == AI else -10

    return 0

def minimax(board, depth, is_max):
    score = evaluate(board)

    # Base cases: game finished
    if score == 10:
        return score - depth  # Prefer faster wins
    if score == -10:
        return score + depth  # Prefer slower losses
    if not is_moves_left(board):
        return 0

    if is_max:
        best = -math.inf
        for i in range(3):
            for j in range(3):
                if board[i][j] == EMPTY:
                    board[i][j] = AI
                    best = max(best, minimax(board, depth + 1, False))
                    board[i][j] = EMPTY
        return best
    else:
        best = math.inf
        for i in range(3):
            for j in range(3):
                if board[i][j] == EMPTY:
                    board[i][j] = HUMAN
                    best = min(best, minimax(board, depth + 1, True))
                    board[i][j] = EMPTY
        return best

def find_best_move(board):
    best_val = -math.inf
    best_move = (-1, -1)

    for i in range(3):
        for j in range(3):
            if board[i][j] == EMPTY:
                board[i][j] = AI
                move_val = minimax(board, 0, False)
                board[i][j] = EMPTY

                if move_val > best_val:
                    best_move = (i, j)
                    best_val = move_val

    return best_move

def play_game():
    board = [[EMPTY for _ in range(3)] for _ in range(3)]
    print("Welcome to Tic-Tac-Toe! You are 'X' and AI is 'O'.")
    print("Enter position coordinates as row (0-2) and column (0-2) separated by a space.")
    print_board(board)

    while True:
        # Human turn
        while True:
            try:
                user_input = input("Enter your move (row col, e.g., '0 2'): ")
                row, col = map(int, user_input.split())
                if board[row][col] == EMPTY:
                    board[row][col] = HUMAN
                    break
                else:
                    print("Cell is already occupied. Choose another!")
            except (ValueError, IndexError):
                print("Invalid input. Enter row (0-2) and column (0-2) separated by a space.")

        print_board(board)

        if evaluate(board) == -10:
            print("Congratulations! You won!")
            break
        if not is_moves_left(board):
            print("It's a draw!")
            break

        # AI turn
        print("AI is making a move...")
        ai_row, ai_col = find_best_move(board)
        board[ai_row][ai_col] = AI
        print_board(board)

        if evaluate(board) == 10:
            print("AI wins! Better luck next time.")
            break
        if not is_moves_left(board):
            print("It's a draw!")
            break

# Run the game
play_game()

def vacuum_cleaner_agent():
    print("--- VACUUM CLEANER AGENT ---")

    # Take initial state inputs
    location = input("Enter initial location of Vacuum Cleaner (A/B): ").strip().upper()
    status_a = input("Enter status of Room A (DIRTY/CLEAN): ").strip().upper()
    status_b = input("Enter status of Room B (DIRTY/CLEAN): ").strip().upper()

    # Dictionary to store environment state
    environment = {'A': status_a, 'B': status_b}
    cost = 0

    print(f"\nInitial State: Location = {location}, Room A = {environment['A']}, Room B = {environment['B']}\n")

    # Clean until both rooms are clean
    while environment['A'] == 'DIRTY' or environment['B'] == 'DIRTY':
        print(f"Current Position: Room {location}")

        # Action in current room
        if environment[location] == 'DIRTY':
            print(f"Action: SUCK (Cleaning Room {location})")
            environment[location] = 'CLEAN'
            cost += 1
        else:
            print(f"Action: Room {location} is already CLEAN")

        # Movement logic between rooms
        if environment['A'] == 'DIRTY' or environment['B'] == 'DIRTY':
            if location == 'A':
                print("Action: Move RIGHT to Room B\n")
                location = 'B'
                cost += 1
            elif location == 'B':
                print("Action: Move LEFT to Room A\n")
                location = 'A'
                cost += 1

    print("---------------------------------------")
    print("GOAL STATE REACHED: Both rooms are CLEAN!")
    print(f"Final State: Room A = {environment['A']}, Room B = {environment['B']}")
    print(f"Total Performance Cost: {cost} action(s)")

# Run the program
vacuum_cleaner_agent()